api_platform:
    title: Teka
    version: 1.0.0
    show_webby: false
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
    exception_to_status:
        App\IdentityAccess\Domain\Exception\EmailAlreadyUsedException: 409
        App\Shared\Domain\Exception\InvalidEmailException: 400
        App\IdentityAccess\Domain\Exception\InvalidVerificationTokenException: 400
        App\IdentityAccess\Domain\Exception\UserNotFoundException: 404
        App\IdentityAccess\Domain\Exception\EmailAlreadyVerifiedException: 409
