doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"
        types:
            user_id: App\IdentityAccess\Infrastructure\Doctrine\Type\UserIdType
            email: App\Shared\Infrastructure\Doctrine\Type\EmailType
            slug: App\Shared\Infrastructure\Doctrine\Type\SlugType
            company_id: App\Company\Infrastructure\Doctrine\Type\CompanyIdType
            company_user_id: App\Company\Infrastructure\Doctrine\Type\CompanyUserIdType
            company_branding: App\Company\Infrastructure\Doctrine\Type\BrandingType
            company_member_id: App\Company\Infrastructure\Doctrine\Type\CompanyMemberIdType
            candidate_profile_id: App\CandidateProfile\Infrastructure\Doctrine\Type\CandidateProfileIdType
            candidate_user_id: App\CandidateProfile\Infrastructure\Doctrine\Type\CandidateUserIdType
            candidate_location: App\CandidateProfile\Infrastructure\Doctrine\Type\LocationType
            candidate_availability: App\CandidateProfile\Infrastructure\Doctrine\Type\AvailabilityType

        profiling_collect_backtrace: "%kernel.debug%"
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            IdentityAccess:
                type: xml
                is_bundle: false
                dir: "%kernel.project_dir%/src/IdentityAccess/Infrastructure/Doctrine/mapping"
                prefix: 'App\IdentityAccess\Domain\Model'
                alias: IdentityAccess
            Company:
                type: xml
                is_bundle: false
                dir: "%kernel.project_dir%/src/Company/Infrastructure/Doctrine/mapping"
                prefix: 'App\Company\Domain\Model'
                alias: Company
            CandidateProfile:
                type: xml
                is_bundle: false
                dir: "%kernel.project_dir%/src/CandidateProfile/Infrastructure/Doctrine/mapping"
                prefix: 'App\CandidateProfile\Domain\Model'
                alias: CandidateProfile

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
